package com.wyz.lidsleepx.app.ui

enum class AppLanguage(val code: String) {
    ENGLISH("en"),
    SIMPLIFIED_CHINESE("zh-CN");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) }
                ?: if (java.util.Locale.getDefault().language == "zh") SIMPLIFIED_CHINESE else ENGLISH
        }
    }
}

data class Strings(
    val appName: String,
    val battery: (String) -> String,
    val charging: String,
    val discharging: String,
    val charged: String,
    val unknown: String,
    val sleepNow: String,
    val displaySleepNow: String,
    val enabled: String,
    val preventIdleSleep: String,
    val preventLidSleep: String,
    val cancelAfter: String,
    val settings: String,
    val language: String,
    val checkUpdates: String,
    val installHelper: String,
    val uninstallHelper: String,
    val helperInstalled: String,
    val helperNotInstalled: String,
    val helperOutdated: String,
    val viewLog: String,
    val exportLog: String,
    val about: String,
    val quit: String,
    val overview: String,
    val lid: String,
    val idle: String,
    val general: String,
    val lowBatterySleep: String,
    val lowBatteryCapacity: String,
    val lowRemainingTime: String,
    val minutes: String,
    val disableIdleOnPower: String,
    val disableLidOnPower: String,
    val immediateSleepOnLid: String,
    val notifications: String,
    val updateChecks: String,
    val launchAtLogin: String,
    val sleepMode: String,
    val sleepMode0: String,
    val sleepMode3: String,
    val sleepMode25: String,
    val clearConfig: String,
    val clearConfigConfirm: String,
    val clearConfigDone: String,
    val sleepModeError: String,
    val launchAtLoginError: String,
    val install: String,
    val later: String,
    val welcomeTitle: String,
    val welcomeBody: String,
    val updateAvailable: String,
    val upToDate: String,
    val updateError: String,
    val helperInstallError: String,
    val helperUninstallError: String,
    val close: String,
    val save: String,
    val invalidNumber: String,
    val logExported: String,
    val logExportError: String,
    val version: String,
    val aboutBody: String,
    val idleRemaining: (String) -> String,
    val lidRemaining: (String) -> String,
)

private val EnglishStrings = Strings(
    appName = "LidSleepX",
    battery = { "Battery: $it" },
    charging = "Charging",
    discharging = "On battery",
    charged = "Charged",
    unknown = "Unknown",
    sleepNow = "Sleep Now",
    displaySleepNow = "Turn Display Off",
    enabled = "Enabled",
    preventIdleSleep = "Prevent Idle Sleep",
    preventLidSleep = "Prevent Lid Sleep",
    cancelAfter = "Cancel After",
    settings = "Settings…",
    language = "Language",
    checkUpdates = "Check for Updates",
    installHelper = "Install Helper…",
    uninstallHelper = "Uninstall Helper…",
    helperInstalled = "Helper: Installed",
    helperNotInstalled = "Helper: Not Installed",
    helperOutdated = "Helper: Update Required",
    viewLog = "View Log",
    exportLog = "Export Log…",
    about = "About LidSleepX",
    quit = "Quit",
    overview = "Overview",
    lid = "Lid",
    idle = "Idle",
    general = "General",
    lowBatterySleep = "Sleep on low battery",
    lowBatteryCapacity = "Battery threshold (%)",
    lowRemainingTime = "Remaining time threshold (minutes)",
    minutes = "minutes",
    disableIdleOnPower = "Prevent idle sleep while charging",
    disableLidOnPower = "Prevent lid sleep while charging",
    immediateSleepOnLid = "Sleep immediately when the lid closes",
    notifications = "Notifications",
    updateChecks = "Check for updates",
    launchAtLogin = "Launch at login",
    sleepMode = "Sleep mode",
    sleepMode0 = "Mode 0 · Memory",
    sleepMode3 = "Mode 3 · Safe sleep",
    sleepMode25 = "Mode 25 · Hibernate",
    clearConfig = "Clear Configuration…",
    clearConfigConfirm = "Reset all LidSleepX settings to their default values?",
    clearConfigDone = "Configuration cleared.",
    sleepModeError = "Sleep mode change failed.",
    launchAtLoginError = "Launch-at-login change failed.",
    install = "Install",
    later = "Later",
    welcomeTitle = "Privileged helper",
    welcomeBody = "LidSleepX needs a helper to change macOS sleep settings. The helper accepts only version checks, disablesleep, and hibernatemode commands.",
    updateAvailable = "Update available",
    upToDate = "LidSleepX is up to date.",
    updateError = "Update check failed.",
    helperInstallError = "Helper installation failed.",
    helperUninstallError = "Helper removal failed.",
    close = "Close",
    save = "Save",
    invalidNumber = "Enter a valid number.",
    logExported = "Log exported",
    logExportError = "Log export failed",
    version = "Version",
    aboutBody = "A menu-bar app that controls macOS sleep behavior for battery and lid events.",
    idleRemaining = { "Idle prevention ends in $it" },
    lidRemaining = { "Lid prevention ends in $it" },
)

private val ChineseStrings = Strings(
    appName = "LidSleepX",
    battery = { "电池：$it" },
    charging = "正在充电",
    discharging = "使用电池",
    charged = "已充满",
    unknown = "未知",
    sleepNow = "立即睡眠",
    displaySleepNow = "关闭显示器",
    enabled = "启用",
    preventIdleSleep = "阻止闲置睡眠",
    preventLidSleep = "阻止合盖睡眠",
    cancelAfter = "定时取消",
    settings = "设置…",
    language = "语言",
    checkUpdates = "检查更新",
    installHelper = "安装助手…",
    uninstallHelper = "卸载助手…",
    helperInstalled = "助手：已安装",
    helperNotInstalled = "助手：未安装",
    helperOutdated = "助手：需要更新",
    viewLog = "查看日志",
    exportLog = "导出日志…",
    about = "关于 LidSleepX",
    quit = "退出",
    overview = "概览",
    lid = "合盖",
    idle = "闲置",
    general = "通用",
    lowBatterySleep = "低电量时睡眠",
    lowBatteryCapacity = "电量阈值（%）",
    lowRemainingTime = "剩余时间阈值（分钟）",
    minutes = "分钟",
    disableIdleOnPower = "充电时阻止闲置睡眠",
    disableLidOnPower = "充电时阻止合盖睡眠",
    immediateSleepOnLid = "合盖后立即睡眠",
    notifications = "通知",
    updateChecks = "检查更新",
    launchAtLogin = "登录时启动",
    sleepMode = "睡眠模式",
    sleepMode0 = "模式 0 · 内存",
    sleepMode3 = "模式 3 · 安全睡眠",
    sleepMode25 = "模式 25 · 休眠",
    clearConfig = "清除配置…",
    clearConfigConfirm = "将 LidSleepX 的全部设置恢复为默认值？",
    clearConfigDone = "配置已清除。",
    sleepModeError = "睡眠模式修改失败。",
    launchAtLoginError = "登录启动修改失败。",
    install = "安装",
    later = "稍后",
    welcomeTitle = "特权助手",
    welcomeBody = "LidSleepX 需要助手修改 macOS 睡眠设置。助手只接受版本检查、disablesleep 和 hibernatemode 命令。",
    updateAvailable = "发现新版本",
    upToDate = "LidSleepX 已是最新版本。",
    updateError = "更新检查失败。",
    helperInstallError = "助手安装失败。",
    helperUninstallError = "助手卸载失败。",
    close = "关闭",
    save = "保存",
    invalidNumber = "请输入有效数字。",
    logExported = "日志已导出",
    logExportError = "日志导出失败",
    version = "版本",
    aboutBody = "此菜单栏应用根据电池和合盖事件控制 macOS 睡眠行为。",
    idleRemaining = { "闲置阻止将在 $it 后结束" },
    lidRemaining = { "合盖阻止将在 $it 后结束" },
)

fun stringsFor(language: AppLanguage): Strings = when (language) {
    AppLanguage.ENGLISH -> EnglishStrings
    AppLanguage.SIMPLIFIED_CHINESE -> ChineseStrings
}

fun formatDuration(seconds: Long, language: AppLanguage): String {
    val hours = seconds / 3600
    val minutes = (seconds % 3600) / 60
    return when {
        language == AppLanguage.SIMPLIFIED_CHINESE && hours > 0 -> "${hours}小时${minutes}分"
        language == AppLanguage.SIMPLIFIED_CHINESE -> "${seconds / 60}分"
        hours > 0 -> "${hours}h ${minutes}m"
        else -> "${seconds / 60}m"
    }
}
