package com.wyz.macisland.app.ui

enum class AppLanguage(val code: String) {
    ENGLISH("en"),
    SIMPLIFIED_CHINESE("zh-CN");

    companion object {
        fun fromCode(code: String?): AppLanguage {
            return entries.firstOrNull { it.code.equals(code, ignoreCase = true) }
                ?: if (java.util.Locale.getDefault().language == "zh") SIMPLIFIED_CHINESE else ENGLISH
        }
    }
}

data class Strings(
    val appName: String,
    val battery: (String) -> String,
    val charging: String,
    val discharging: String,
    val charged: String,
    val unknown: String,
    val sleepNow: String,
    val displaySleepNow: String,
    val enabled: String,
    val preventIdleSleep: String,
    val preventLidSleep: String,
    val cancelAfter: String,
    val settings: String,
    val language: String,
    val checkUpdates: String,
    val installHelper: String,
    val uninstallHelper: String,
    val helperInstalled: String,
    val helperNotInstalled: String,
    val helperOutdated: String,
    val viewLog: String,
    val exportLog: String,
    val about: String,
    val quit: String,
    val overview: String,
    val lid: String,
    val idle: String,
    val general: String,
    val shelf: String,
    val shelfEnabled: String,
    val screenshotInbox: String,
    val screenshotInboxHelp: String,
    val shelfSounds: String,
    val shelfStatus: String,
    val shelfEmpty: String,
    val showShelf: String,
    val clearShelf: String,
    val openScreenshotDirectory: String,
    val screenshotTakeoverOn: String,
    val screenshotTakeoverOff: String,
    val screenshotTakeoverError: String,
    val screenshotRestoreError: String,
    val screenshotDirectoryError: String,
    val screenshotCopyError: String,
    val screenshotOpenError: String,
    val screenshotMarkupError: String,
    val screenshotMoveError: String,
    val screenshotCopy: String,
    val screenshotPreview: String,
    val screenshotMarkup: String,
    val screenshotRemove: String,
    val lowBatterySleep: String,
    val lowBatteryCapacity: String,
    val lowRemainingTime: String,
    val minutes: String,
    val disableIdleOnPower: String,
    val disableLidOnPower: String,
    val disableLidOnBattery: String,
    val batteryLidWarning: String,
    val immediateSleepOnLid: String,
    val darkWakeAwareness: String,
    val darkWakeStatus: String,
    val darkWakeScanning: String,
    val darkWakeUnavailable: String,
    val darkWakeLast: String,
    val darkWakeReason: String,
    val darkWakeCount24h: String,
    val notifications: String,
    val updateChecks: String,
    val launchAtLogin: String,
    val sleepMode: String,
    val sleepMode0: String,
    val sleepMode3: String,
    val sleepMode25: String,
    val clearConfig: String,
    val clearConfigConfirm: String,
    val clearConfigDone: String,
    val sleepModeError: String,
    val launchAtLoginError: String,
    val install: String,
    val later: String,
    val welcomeTitle: String,
    val welcomeBody: String,
    val updateAvailable: String,
    val upToDate: String,
    val updateError: String,
    val helperInstallError: String,
    val helperUninstallError: String,
    val lidPolicyError: String,
    val close: String,
    val save: String,
    val invalidNumber: String,
    val logExported: String,
    val logExportError: String,
    val version: String,
    val aboutBody: String,
    val idleRemaining: (String) -> String,
    val lidRemaining: (String) -> String,
)

private val EnglishStrings = Strings(
    appName = "MacIsland",
    battery = { "Battery: $it" },
    charging = "Charging",
    discharging = "On battery",
    charged = "Charged",
    unknown = "Unknown",
    sleepNow = "Sleep Now",
    displaySleepNow = "Turn Display Off",
    enabled = "Enabled",
    preventIdleSleep = "Prevent Idle Sleep",
    preventLidSleep = "Prevent Lid Sleep",
    cancelAfter = "Cancel After",
    settings = "Settings…",
    language = "Language",
    checkUpdates = "Check for Updates",
    installHelper = "Install Helper…",
    uninstallHelper = "Uninstall Helper…",
    helperInstalled = "Helper: Installed",
    helperNotInstalled = "Helper: Not Installed",
    helperOutdated = "Helper: Update Required",
    viewLog = "View Log",
    exportLog = "Export Log…",
    about = "About MacIsland",
    quit = "Quit",
    overview = "Overview",
    lid = "Lid",
    idle = "Idle",
    general = "General",
    shelf = "Top Shelf",
    shelfEnabled = "Show screenshot shelf",
    screenshotInbox = "Take over screenshots",
    screenshotInboxHelp = "Save screenshots to MacIsland and hide the system thumbnail.",
    shelfSounds = "Screenshot sounds",
    shelfStatus = "Shelf status",
    shelfEmpty = "No screenshots",
    showShelf = "Show Shelf",
    clearShelf = "Clear Shelf",
    openScreenshotDirectory = "Open Screenshot Folder",
    screenshotTakeoverOn = "Screenshots are managed by MacIsland.",
    screenshotTakeoverOff = "System screenshot settings are restored.",
    screenshotTakeoverError = "Screenshot takeover failed.",
    screenshotRestoreError = "System screenshot settings were not restored.",
    screenshotDirectoryError = "Cannot open the screenshot folder.",
    screenshotCopyError = "Cannot copy the screenshot.",
    screenshotOpenError = "Cannot open the screenshot.",
    screenshotMarkupError = "Cannot open Markup.",
    screenshotMoveError = "The file operation failed.",
    screenshotCopy = "Copy",
    screenshotPreview = "Preview",
    screenshotMarkup = "Markup",
    screenshotRemove = "Remove from Shelf",
    lowBatterySleep = "Sleep on low battery",
    lowBatteryCapacity = "Battery threshold (%)",
    lowRemainingTime = "Remaining time threshold (minutes)",
    minutes = "minutes",
    disableIdleOnPower = "Prevent idle sleep while charging",
    disableLidOnPower = "Prevent lid sleep when connected to power",
    disableLidOnBattery = "Prevent lid sleep on battery power",
    batteryLidWarning = "Warning: this option increases battery drain.",
    immediateSleepOnLid = "Sleep immediately when the lid closes",
    darkWakeAwareness = "DarkWake awareness",
    darkWakeStatus = "DarkWake status",
    darkWakeScanning = "Reading",
    darkWakeUnavailable = "Unavailable",
    darkWakeLast = "Last time",
    darkWakeReason = "Reason",
    darkWakeCount24h = "Count in 24 hours",
    notifications = "Notifications",
    updateChecks = "Check for updates",
    launchAtLogin = "Launch at login",
    sleepMode = "Sleep mode",
    sleepMode0 = "Mode 0 · Memory",
    sleepMode3 = "Mode 3 · Safe sleep",
    sleepMode25 = "Mode 25 · Hibernate",
    clearConfig = "Clear Configuration…",
    clearConfigConfirm = "Reset all MacIsland settings to their default values?",
    clearConfigDone = "Configuration cleared.",
    sleepModeError = "Sleep mode change failed.",
    launchAtLoginError = "Launch-at-login change failed.",
    install = "Install",
    later = "Later",
    welcomeTitle = "Privileged helper",
    welcomeBody = "MacIsland needs a helper to change macOS sleep settings. The helper accepts only version checks, disablesleep, and hibernatemode commands.",
    updateAvailable = "Update available",
    upToDate = "MacIsland is up to date.",
    updateError = "Update check failed.",
    helperInstallError = "Helper installation failed.",
    helperUninstallError = "Helper removal failed.",
    lidPolicyError = "Cannot change lid sleep settings.",
    close = "Close",
    save = "Save",
    invalidNumber = "Enter a valid number.",
    logExported = "Log exported",
    logExportError = "Log export failed",
    version = "Version",
    aboutBody = "A menu-bar app that controls macOS sleep behavior for battery and lid events.",
    idleRemaining = { "Idle prevention ends in $it" },
    lidRemaining = { "Lid prevention ends in $it" },
)

private val ChineseStrings = Strings(
    appName = "MacIsland",
    battery = { "电池：$it" },
    charging = "正在充电",
    discharging = "使用电池",
    charged = "已充满",
    unknown = "未知",
    sleepNow = "立即睡眠",
    displaySleepNow = "关闭显示器",
    enabled = "启用",
    preventIdleSleep = "阻止闲置睡眠",
    preventLidSleep = "阻止合盖睡眠",
    cancelAfter = "定时取消",
    settings = "设置…",
    language = "语言",
    checkUpdates = "检查更新",
    installHelper = "安装助手…",
    uninstallHelper = "卸载助手…",
    helperInstalled = "助手：已安装",
    helperNotInstalled = "助手：未安装",
    helperOutdated = "助手：需要更新",
    viewLog = "查看日志",
    exportLog = "导出日志…",
    about = "关于 MacIsland",
    quit = "退出",
    overview = "概览",
    lid = "合盖",
    idle = "闲置",
    general = "通用",
    shelf = "顶部工具栏",
    shelfEnabled = "显示截图工具栏",
    screenshotInbox = "接管截图",
    screenshotInboxHelp = "将截图保存到 MacIsland，并隐藏系统浮动缩略图。",
    shelfSounds = "截图声音",
    shelfStatus = "工具栏状态",
    shelfEmpty = "没有截图",
    showShelf = "显示工具栏",
    clearShelf = "清空工具栏",
    openScreenshotDirectory = "打开截图目录",
    screenshotTakeoverOn = "截图由 MacIsland 管理。",
    screenshotTakeoverOff = "系统截图设置已恢复。",
    screenshotTakeoverError = "截图接管失败。",
    screenshotRestoreError = "系统截图设置未能恢复。",
    screenshotDirectoryError = "无法打开截图目录。",
    screenshotCopyError = "无法复制截图。",
    screenshotOpenError = "无法打开截图。",
    screenshotMarkupError = "无法打开标记工具。",
    screenshotMoveError = "文件操作失败。",
    screenshotCopy = "复制",
    screenshotPreview = "预览",
    screenshotMarkup = "标记",
    screenshotRemove = "从工具栏移除",
    lowBatterySleep = "低电量时睡眠",
    lowBatteryCapacity = "电量阈值（%）",
    lowRemainingTime = "剩余时间阈值（分钟）",
    minutes = "分钟",
    disableIdleOnPower = "充电时阻止闲置睡眠",
    disableLidOnPower = "接入电源时阻止合盖睡眠",
    disableLidOnBattery = "电池供电时阻止合盖睡眠",
    batteryLidWarning = "警告：此选项会增加电池耗电。",
    immediateSleepOnLid = "合盖后立即睡眠",
    darkWakeAwareness = "DarkWake 感知",
    darkWakeStatus = "DarkWake 状态",
    darkWakeScanning = "读取中",
    darkWakeUnavailable = "不可用",
    darkWakeLast = "最近时间",
    darkWakeReason = "原因",
    darkWakeCount24h = "24 小时次数",
    notifications = "通知",
    updateChecks = "检查更新",
    launchAtLogin = "登录时启动",
    sleepMode = "睡眠模式",
    sleepMode0 = "模式 0 · 内存",
    sleepMode3 = "模式 3 · 安全睡眠",
    sleepMode25 = "模式 25 · 休眠",
    clearConfig = "清除配置…",
    clearConfigConfirm = "将 MacIsland 的全部设置恢复为默认值？",
    clearConfigDone = "配置已清除。",
    sleepModeError = "睡眠模式修改失败。",
    launchAtLoginError = "登录启动修改失败。",
    install = "安装",
    later = "稍后",
    welcomeTitle = "特权助手",
    welcomeBody = "MacIsland 需要助手修改 macOS 睡眠设置。助手只接受版本检查、disablesleep 和 hibernatemode 命令。",
    updateAvailable = "发现新版本",
    upToDate = "MacIsland 已是最新版本。",
    updateError = "更新检查失败。",
    helperInstallError = "助手安装失败。",
    helperUninstallError = "助手卸载失败。",
    lidPolicyError = "无法修改合盖睡眠设置。",
    close = "关闭",
    save = "保存",
    invalidNumber = "请输入有效数字。",
    logExported = "日志已导出",
    logExportError = "日志导出失败",
    version = "版本",
    aboutBody = "此菜单栏应用根据电池和合盖事件控制 macOS 睡眠行为。",
    idleRemaining = { "闲置阻止将在 $it 后结束" },
    lidRemaining = { "合盖阻止将在 $it 后结束" },
)

fun stringsFor(language: AppLanguage): Strings = when (language) {
    AppLanguage.ENGLISH -> EnglishStrings
    AppLanguage.SIMPLIFIED_CHINESE -> ChineseStrings
}

fun formatDuration(seconds: Long, language: AppLanguage): String {
    val hours = seconds / 3600
    val minutes = (seconds % 3600) / 60
    return when {
        language == AppLanguage.SIMPLIFIED_CHINESE && hours > 0 -> "${hours}小时${minutes}分"
        language == AppLanguage.SIMPLIFIED_CHINESE -> "${seconds / 60}分"
        hours > 0 -> "${hours}h ${minutes}m"
        else -> "${seconds / 60}m"
    }
}
